# Generated by Django 3.0.4 on 2020-03-09 11:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(verbose_name='date_of_birth')),
                ('email', models.CharField(max_length=50)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(default=1, max_length=60)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateTimeField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('number_of_adults', models.IntegerField(default=0)),
                ('number_of_children', models.IntegerField(default=0)),
                ('enquiry_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_category', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('price_per_unit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount_per_head', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='purchase date')),
                ('purchase_description', models.CharField(max_length=100)),
                ('purchase_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('salary', models.FloatField(default=0.0)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(verbose_name='booking_date')),
                ('checkin_date', models.DateTimeField(verbose_name='check_in_time')),
                ('checkout_date', models.DateTimeField(verbose_name='check_out_date')),
                ('number_of_people', models.IntegerField(default=0)),
                ('booking_amount', models.FloatField(default=0.0)),
                ('paid_status', models.CharField(max_length=100)),
                ('booking_status', models.CharField(choices=[('p', 'pending'), ('b', 'Booked'), ('c', 'Canceled')], max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.Customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.Package_details')),
            ],
        ),
    ]
