# Generated by Django 3.0.4 on 2020-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation_name',
            field=models.CharField(max_length=60),
        ),
    ]
