# Generated by Django 3.0.5 on 2020-04-18 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0003_auto_20200311_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mode_of_payment',
            field=models.CharField(default=datetime.date, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package_details',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
