# Generated by Django 3.0.5 on 2020-04-18 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0005_auto_20200418_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
