# Generated by Django 3.0.5 on 2020-04-18 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0008_auto_20200418_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 17, 54, 38, 397895)),
        ),
    ]
