# Generated by Django 3.0.5 on 2020-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0010_auto_20200418_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(),
        ),
    ]
